# Generated by Django 4.2.27 on 2025-12-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1542744173-8e7e53415bb0')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
