# Generated by Django 4.2.27 on 2025-12-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='Join us for an incredible networking experience.'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='Link to Eventbrite or payment page'),
        ),
    ]
