# Generated by Django 4.2.27 on 2025-12-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_event_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='price_label',
            field=models.CharField(default='Free', help_text="e.g. '$50' or 'Starting at $99'", max_length=50),
        ),
    ]
