# Generated by Django 4.2.7 on 2026-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='currency',
            field=models.CharField(default='usd', help_text='ISO currency code (e.g. usd, eur, gbp)', max_length=3),
        ),
    ]
