# Generated by Django 4.2.7 on 2026-03-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_ticket_original_price_ticket_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_automation_text',
            field=models.TextField(blank=True, help_text='Custom message sent to ticket purchasers.', null=True),
        ),
    ]
