# Generated by Django 4.2.7 on 2026-03-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_email_automation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_rsvp_only',
            field=models.BooleanField(default=False, help_text='If true, users can RSVP without selecting a ticket tier.'),
        ),
    ]
