# Generated by Django 4.2.7 on 2026-04-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_ticket_email_ticket_first_name_ticket_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspeaker',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
