# Generated by Django 4.2.7 on 2026-04-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventspeaker_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1542744173-8e7e53415bb0', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='Link to Eventbrite or external payment page (optional)', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='virtual_link',
            field=models.URLField(blank=True, help_text='Zoom/Meet link for virtual events', max_length=500, null=True),
        ),
    ]
