# Generated by Django 4.2.7 on 2026-04-02 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_alter_event_image_url_alter_event_ticket_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
