# Generated by Django 4.2.7 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('text', 'Text'),
                    ('image', 'Image'),
                    ('audio', 'Audio/Voice'),
                    ('video', 'Video'),
                    ('document', 'Document'),
                ],
                default='text',
                max_length=10,
            ),
        ),
    ]
