# Generated by Django 4.2.7 on 2026-01-11 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Defaults to 7 days from now', null=True),
        ),
        migrations.AddField(
            model_name='founderprofile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Select an existing user to auto-fill details', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='founderprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='founder_photos/'),
        ),
    ]
