# Generated by Django 4.2.7 on 2026-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_founderprofile_expires_at_founderprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='business_logos/')),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses of the Month',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
