# Generated by Django 4.2.7 on 2026-02-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_businessofmonth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='founderprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
