# Generated by Django 4.2.7 on 2026-02-19 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_flashalert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessofmonth',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses_of_month', to=settings.AUTH_USER_MODEL),
        ),
    ]
