# Generated by Django 4.2.7 on 2026-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_businessofmonth_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderprofile',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard ($600)'), ('PREMIUM', 'Premium ($800)')], default='FREE', max_length=20),
        ),
    ]
