# Generated by Django 4.2.27 on 2025-12-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.URLField(blank=True, default='https://ui-avatars.com/api/?background=D4AF37&color=fff&name=Founder'),
        ),
    ]
