# Generated by Django 4.2.7 on 2026-01-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('latest_version', models.CharField(help_text='e.g. 1.0.3', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='Force update?')),
                ('update_url', models.URLField(help_text='Play Store or Direct Link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
