# Generated by Django 4.2.27 on 2025-12-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('MAGAZINE', 'Magazine'), ('VIDEO', 'Video Masterclass'), ('TOOLKIT', 'Business Toolkit')], max_length=20)),
                ('url', models.URLField(help_text='Link to the PDF, YouTube video, or Article')),
                ('thumbnail_url', models.URLField(default='https://images.unsplash.com/photo-1497366216548-37526070297c')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
