# Generated by Django 4.2.27 on 2025-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('MAGAZINE', 'Magazine'), ('MASTERCLASS', 'Masterclass'), ('NEWSLETTER', 'Newsletter'), ('TOOLKIT', 'Business Toolkit')], max_length=20),
        ),
    ]
