# Generated by Django 4.2.27 on 2025-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_is_premium_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
