# Generated by Django 4.2.27 on 2025-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Finance'), ('HLTH', 'Healthcare'), ('RET', 'Retail'), ('EDU', 'Education'), ('MED', 'Media & Arts'), ('LEG', 'Legal'), ('FASH', 'Fashion'), ('MAN', 'Manufacturing'), ('OTH', 'Other')], default='OTH', max_length=50),
        ),
    ]
