# Generated by Django 4.2.27 on 2026-01-15 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingrequest',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketing_videos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_notice',
            field=models.TextField(blank=True, help_text='Reason for warning/suspension (visible to user)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='suspension_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketing_assets/'),
        ),
        migrations.AlterField(
            model_name='marketingrequest',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
