# Generated by Django 4.2.27 on 2026-01-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_marketingrequest_video_profile_admin_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Indefinitely blocked by admin'),
        ),
    ]
