# Generated by Django 4.2.7 on 2026-01-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_marketingcomment_marketinglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
