# Generated by Django 4.2.7 on 2026-01-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_read_community_chat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingrequest',
            name='type',
            field=models.CharField(choices=[('AD', 'Advertisement'), ('PROMOTION', 'Promotion'), ('CONTENT', 'VVIP Content')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admin_notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
