# Generated by Django 4.2.7 on 2026-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard ($200)'), ('PREMIUM', 'Premium ($400)')], default='FREE', max_length=20),
        ),
    ]
