# Generated by Django 4.2.7 on 2026-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
