# Generated by Django 4.2.7 on 2026-04-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_businessprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='marketingrequest',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
