# Generated by Django 4.2.7 on 2026-04-10 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_businessprofile_linkedin_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BUSINESS_STATUS', 'Business Status Updated'), ('MARKETING_STATUS', 'Marketing Status Updated'), ('REPORT_STATUS', 'Report Status Updated'), ('MODERATION_ACTION', 'Moderation Action Performed')], max_length=40)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=100)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
