"""
Django settings for ffig_backend project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# SYNC: Backend deployment Check
import os
import dj_database_url


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return int(default)


def unique_ordered(items):
    seen = set()
    ordered = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            ordered.append(item)
    return ordered


def sanitize_hosts(hosts):
    # Explicitly reject wildcard host entries.
    return [host for host in hosts if host and host != '*']


def sanitize_origins(origins):
    cleaned = []
    for origin in origins:
        value = origin.strip().rstrip('/')
        if not value or '*' in value:
            continue
        cleaned.append(value)
    return cleaned

# Load .env file for local development
env_path = Path(__file__).resolve().parent.parent / '.env'
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            if line.strip() and not line.startswith('#'):
                try:
                    key, value = line.strip().split('=', 1)
                    # Strip quotes if present
                    if value.startswith("'") and value.endswith("'"):
                        value = value[1:-1]
                    elif value.startswith('"') and value.endswith('"'):
                        value = value[1:-1]
                    os.environ[key] = value
                except ValueError:
                    pass

# Log the Database Host for verification (Safe for debugging)
if env_bool('DEBUG', False) and os.environ.get('DATABASE_URL'):
    from dj_database_url import parse as db_url_parse
    db_config = db_url_parse(os.environ.get('DATABASE_URL'))
    print(f"📡 Database Host: {db_config.get('HOST')}")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if env_bool('DEBUG', False):
        SECRET_KEY = 'django-insecure-local-development-key-change-me'
    else:
        raise RuntimeError('SECRET_KEY must be set in non-debug environments.')

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

LOCAL_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.0.2.2',
    '192.168.0.5',
]
KNOWN_PROD_ALLOWED_HOSTS = [
    'ffig-backend-ti5w.onrender.com',
    'femalefoundersinitiativeglobal.onrender.com',
    'www.femalefoundersinitiative.com',
    'femalefoundersinitiative.com',
    'www.femalefoundersinitiativeglobal.com',
    'femalefoundersinitiativeglobal.com',
]
LOCAL_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.0.5',
    'http://192.168.0.5:8000',
]
KNOWN_PROD_TRUSTED_ORIGINS = [
    'https://ffig-backend-ti5w.onrender.com',
    'https://femalefoundersinitiativeglobal.onrender.com',
    'https://www.femalefoundersinitiative.com',
    'https://femalefoundersinitiative.com',
    'https://www.femalefoundersinitiativeglobal.com',
    'https://femalefoundersinitiativeglobal.com',
]
LOCAL_CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.0.5:8000',
]

env_allowed_hosts = sanitize_hosts(env_list('ALLOWED_HOSTS', ''))
env_csrf_trusted_origins = sanitize_origins(env_list('CSRF_TRUSTED_ORIGINS', ''))
env_cors_allowed_origins = sanitize_origins(env_list('CORS_ALLOWED_ORIGINS', ''))

# Automatically append Render hostnames if running on Render
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()

if DEBUG:
    # Local-first defaults for development.
    ALLOWED_HOSTS = unique_ordered(env_allowed_hosts or LOCAL_ALLOWED_HOSTS)
    CSRF_TRUSTED_ORIGINS = unique_ordered(env_csrf_trusted_origins or LOCAL_TRUSTED_ORIGINS)
    CORS_ALLOWED_ORIGINS = unique_ordered(env_cors_allowed_origins or LOCAL_CORS_ALLOWED_ORIGINS)
else:
    # Mobile-only production posture: explicit backend/admin origins only.
    ALLOWED_HOSTS = unique_ordered(env_allowed_hosts + KNOWN_PROD_ALLOWED_HOSTS)
    if render_external_hostname:
        ALLOWED_HOSTS = unique_ordered(ALLOWED_HOSTS + [render_external_hostname])

    CSRF_TRUSTED_ORIGINS = unique_ordered(env_csrf_trusted_origins + KNOWN_PROD_TRUSTED_ORIGINS)
    if render_external_hostname:
        CSRF_TRUSTED_ORIGINS = unique_ordered(CSRF_TRUSTED_ORIGINS + [f'https://{render_external_hostname}'])

    # Keep CORS strict in production. Native mobile apps do not require browser CORS.
    CORS_ALLOWED_ORIGINS = unique_ordered(env_cors_allowed_origins)

if env_bool('CORS_ALLOW_ALL_ORIGINS', False):
    print("⚠️  WARNING: CORS_ALLOW_ALL_ORIGINS=True was provided but is ignored for security hardening.")

CORS_ALLOW_ALL_ORIGINS = False

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'authentication',
    'corsheaders',
    'events',
    'members',
    'resources',
    'chat',
    'home',
    'storages',
    'core',
    'payments',
    'community',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.UpdateLastSeenMiddleware',
    'core.middleware.RequireActiveMembershipMiddleware',
]

ROOT_URLCONF = 'ffig_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ffig_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATA BASE CONFIGURATION
# If there is a DATABASE_URL environment variable (Render), use it.
# Otherwise, use your local sqlite file.
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=60, # Keep connections for 60 seconds
        conn_health_checks=True, # Added in Django 4.1+
    )
}

# Strict Check: Do not allow SQLite on Render
if os.environ.get('RENDER') and 'sqlite' in DATABASES['default']['ENGINE']:
    raise RuntimeError("❌ FATAL: Render detected but DATABASE_URL is missing! You must configure the Postgres URL in Environment Variables.")

# Debug: Print DB Engine to logs (Safe for ephemeral logs)
if DEBUG:
    print(f"🚀 Database Engine Configured: {DATABASES['default']['ENGINE']}")
    if 'sqlite' in DATABASES['default']['ENGINE']:
        print("⚠️  WARNING: Using SQLite. Data will be lost on ephemeral environments like Render!")
        if os.environ.get('RENDER'):
            print("❌ CRITICAL: Render detected but DATABASE_URL not found!")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mobile_app', 'web'),
]

# FIX: Define this ALWAYS, not just in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Enable Whitenoise to compress files (But NO Manifest hashing, so filename stays same)
# Enable Whitenoise to compress files (But NO Manifest hashing, so filename stays same)
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'  <-- Removed to avoid conflict

# Media Files (User Uploads)
# Media Files (User Uploads)
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-north-1')

if AWS_ACCESS_KEY_ID and AWS_STORAGE_BUCKET_NAME:
    print(f"🚀 Storage Configured: AWS S3 (Bucket: {AWS_STORAGE_BUCKET_NAME})")
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "default_acl": None, 
                "querystring_auth": True,
                "object_parameters": {
                    "CacheControl": "max-age=86400",
                },
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'
else:
    # Local Storage fallback
    print("⚠️  WARNING: AWS Keys missing. Falling back to Local Storage (FileSystem).")
    
    # SAFETY CHECK: If on Render (Production) but keys are missing, WARN LOUDLY or FAIL.
    if os.environ.get('RENDER'):
        print("❌ CRITICAL: Running on Render without AWS Keys! Uploads will be LOST on redeploy.")
        # Uncomment the next line to strictly enforce S3 on production (Recommended)
        # raise RuntimeError("🔥 FATAL: AWS Credentials missing in Production! Add AWS_ACCESS_KEY_ID and AWS_STORAGE_BUCKET_NAME.")

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    # Transitional defaults: significantly shorter than 10 years while minimizing
    # forced logouts until client-side silent refresh is fully centralized.
    'ACCESS_TOKEN_LIFETIME': timedelta(days=env_int('JWT_ACCESS_DAYS', 30)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int('JWT_REFRESH_DAYS', 365)),
    'ROTATE_REFRESH_TOKENS': env_bool('JWT_ROTATE_REFRESH_TOKENS', True),
    # Set to True only after enabling token blacklist app + migrations.
    'BLACKLIST_AFTER_ROTATION': env_bool('JWT_BLACKLIST_AFTER_ROTATION', False),
}

# Chat safety defaults
CHAT_MESSAGE_DELETE_WINDOW_MINUTES = env_int('CHAT_MESSAGE_DELETE_WINDOW_MINUTES', 15)

REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = [
    'rest_framework.throttling.AnonRateThrottle',
    'rest_framework.throttling.UserRateThrottle',
]
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
    'anon': os.environ.get('DRF_THROTTLE_ANON', '60/minute'),
    'user': os.environ.get('DRF_THROTTLE_USER', '120/minute'),
}

# Email Configuration (AWS SES via SMTP)
# Make sure to add these to your Render environment variables and local .env
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'email-smtp.us-east-1.amazonaws.com') # Your SES SMTP endpoint
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '') # Your SMTP Username
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '') # Your SMTP Password
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'admin@femalefoundersinitiative.com')

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
