# Generated by Django 4.2.27 on 2025-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('GEN', 'General Resource'), ('MAG', 'Magazine'), ('NEWS', 'Newsletter'), ('CLASS', 'Masterclass'), ('POD', 'Podcast')], default='GEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(),
        ),
    ]
